name: Node.js CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          node scripts/js/asn.js
          node scripts/js/getfiles.js
          node scripts/js/filterrules.js
          node scripts/js/mergerules.js
          node scripts/js/chnroutes.js
          node scripts/js/adgfilter.js

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto Update
